trigger:
  branches:
    include:
      - 'dev'
      - 'test'
      - 'prod'

variables:
- group: Fabric_Deployment_Group_S
- group: Fabric_Deployment_Group_NS

pool:
  name: Azure Pipelines


stages:
- stage: Test
  displayName: 'Update From Git'
  jobs:
    - deployment: 'UpdateFromGit'
      displayName: 'Run Update'
      ${{if contains(variables['Build.SourceBranch'], 'dev')}}:
        environment: 'dev'
      ${{if contains(variables['Build.SourceBranch'], 'test')}}:
        environment: 'test'
      ${{if contains(variables['Build.SourceBranch'], 'prod')}}:
        environment: 'prod'

      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
              path: 'self'

            - task: PowerShell@2
              inputs:
                targetType: 'inline'
                script: |
                  Write-Host "Starting script execution..."
                  Write-Host "Branch Name: $env:branchName"
                  if ($env:branchName -eq 'dev') {
                    $DeployToWorkspaceName = '$(devWorkspaceName)'
                  } elseif ($env:branchName -eq 'test') {
                    $DeployToWorkspaceName = '$(tstWorkspaceName)'
                  } elseif ($env:branchName -eq 'prod') {
                    $DeployToWorkspaceName = '$(prdWorkspaceName)'
                  } else {
                    $DeployToWorkspaceName = 'UnknownBranch'
                  }

                  # Install Az module
                  Install-Module -Name Az -Force -Scope CurrentUser
                  # Import Az module
                  Import-Module Az
                  # Run your script
                  Write-Host "Running update script passing parameter workspaceName=$DeployToWorkspaceName"
                  .\scripts\updatefromgit.ps1 -workspaceName $DeployToWorkspaceName -pFabricToken $(fabrictoken)
