# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - 'dev'
      - 'test'
      - 'prod'

variables:
- group: Fabric_Deployment_Group_S
- group: Fabric_Deployment_Group_NS

pool:
  name: Azure Pipelines


stages:
- stage: Test
  displayName: 'Update From Git'
  jobs:
    - deployment: 'UpdateFromGit'
      displayName: 'Run Update'
      environment: $env:branchName
      strategy:
        runOnce:
          deploy:
            steps:
            - task: PowerShell@2
              inputs:
                targetType: 'inline'
                script: |
              
                  if ($env:branchName -eq 'dev') {
                      $DeployToWorkspaceName = '$(devWorkspaceName)'
                    } elseif ($env:branchName -eq 'test') {
                      $DeployToWorkspaceName = '$(tstWorkspaceName)'
                    } elseif ($env:branchName -eq 'prod') {
                      $DeployToWorkspaceName = '$(prdWorkspaceName)'
                    } else {
                      $workspace = 'UnknownBranch'
                    }
                  fi

                  # Install Az module
                  Install-Module -Name Az -Force -Scope CurrentUser

                  # Import Az module
                  Import-Module Az

                  # Run your script
                  .\scripts\updatefromgit.ps1 -workspaceName $(DeployToWorkspaceName) -pFabricToken $(fabrictoken)

